[workspace]
members = [ "src/vtok_p11", "src/vtok_rpc", "src/vtok_srv", "src/vtok_tool" ]
default-members = ["src/vtok_p11", "src/vtok_rpc", "src/vtok_srv", "src/vtok_tool" ]

[profile.release]
lto = true
