header = """
/*
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * Licensed under the Amazon Software License
*/"""

tab_width = 4
language = "C"
cpp_compat = true

include_guard = "NSM_LIB_H"

[parse]
parse_deps = true
include = ["nsm-io"]

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
