[package]
name = "vtok_init"
version = "0.1.0"
authors = ["The AWS Nitro Enclaves Team <aws-nitro-enclaves-devel@amazon.com>"]
edition = "2018"
description = "p11ne enclave init application"

[[bin]]
name = "p11ne-init"
path = "src/main.rs"
