#!/bin/bash

# Collect the arguments after the script name
CLI_ARGS="$@"

if [ -z "$CLI_ARGS" ] || [ "$CLI_ARGS" == "-h" ] || [ "$CLI_ARGS" == "--help" ]; then
  npx ts-node --prefer-ts-exts src/bin/cli.ts -h
  exit 0
fi

# Run CDK deploy with the synthesized CLI command
CLI_COMMAND="npx ts-node --prefer-ts-exts src/bin/cli.ts ${CLI_ARGS}"
cdk deploy --all --require-approval never --app \""${CLI_COMMAND}"\"
